# Generated by Django 4.1 on 2022-10-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeloRelacionalBaseDeDatos', '0002_alter_empresas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_app',
            name='contraseña',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario_app',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario_app',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario_app',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
    ]
