# Generated by Django 4.1 on 2022-10-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeloRelacionalBaseDeDatos', '0003_alter_usuario_app_contraseña_alter_usuario_app_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_app',
            name='contraseña',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario_app',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario_app',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario_app',
            name='usuario',
            field=models.CharField(max_length=45),
        ),
    ]
