# Generated by Django 4.1 on 2022-10-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeloRelacionalBaseDeDatos', '0004_alter_usuario_app_contraseña_alter_usuario_app_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantes',
            name='valor',
            field=models.IntegerField(default=None, verbose_name=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte_contable',
            name='monto',
            field=models.IntegerField(default=None, verbose_name=45),
            preserve_default=False,
        ),
    ]
